apiVersion: v1
kind: ConfigMap
metadata:
  name: env-configmap
data:
  POSTGRES_HOST: hieudevpostgress.cad4oj2nucpu.us-east-1.rds.amazonaws.com
  POSTGRES_DB: postgres
  AWS_BUCKET: test-010440084304-dev
  AWS_REGION: us-east-1
  AWS_PROFILE: default
  URL: http://localhost:8100
